// Code generated by command: go run main.go -out avo_amd64.s -stubs avo_amd64.go. DO NOT EDIT.

#include "textflag.h"

// func AccumulateAvo(b []byte) uint64
// Requires: SSE2, SSE4.1
TEXT ·AccumulateAvo(SB), NOSPLIT, $0-32
	MOVQ b_len+8(FP), AX
	MOVQ b_base+0(FP), CX
	PXOR X0, X0
	PXOR X1, X1

loop:
	CMPQ   AX, $0x00
	JE     done
	MOVOU  (CX), X2
	PSADBW X1, X2
	ADDQ   $0x10, CX
	PADDQ  X2, X0
	SUBQ   $0x10, AX
	JMP    loop

done:
	// Store sum to return value.
	MOVQ   X0, AX
	PEXTRQ $0x01, X0, CX
	ADDQ   CX, AX
	MOVQ   AX, ret+24(FP)
	RET
